### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Thermatix** [jdm/ruby-mri-rs#1]
Being primarily a rubist that wants to branch out into rust, any thing that makes combining the two easier is of great interest. I did glance through the source but I'd like some more definitives, so without ado I have some questions:

1. How much of the ruby API is implemented?
2. Any examples? (even something basic just to get you going would be of great help)

I think that's it.

**Comment by jdm** [comment]
Very little. I reccommend looking at the [mrusty](https://crates.io/crates/mrusty) crate instead, which is focused on bindings to a Ruby implementation that's intended for embedding.

**Comment by Thermatix** [comment]
Yeah, I did see that, I just felt that this crate seemed to be more aimed towards making it easier to call out from ruby to rust then embedding ruby in rust, thus making it easier to build rust based extensions.

**Comment by jdm** [comment]
Oh, for Rust-based extensions you almost certainly want the [ruru](https://crates.io/crates/ruru) crate (and [rurust](https://crates.io/crates/rurust) looks like it's doing what this library does but much better).

**Comment by Thermatix** [comment]
Fair enough, does that mean you have no plans to develop crate in favour of using ruru or rurust?

**Comment by jdm** [comment]
Yeah, I haven't touched this in 1.5 years. I got distracted by other things.

**Comment by Thermatix** [comment]
Ok, cool, well thanks for your help.
